# Generated by Django 4.1.5 on 2023-02-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('key', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=256)),
                ('value_type', models.CharField(choices=[('int', 'int'), ('str', 'str'), ('bool', 'bool')], default='str', max_length=8)),
                ('editable', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=False, help_text='is visible to normal user')),
                ('help_text', models.CharField(blank=True, max_length=256, null=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
