# Generated by Django 4.1.5 on 2023-01-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cs', '0004_alter_chargingstation_power_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingsocket',
            name='is_charging',
            field=models.BooleanField(default=False),
        ),
    ]
