# Generated by Django 4.1.5 on 2023-02-02 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cs', '0005_chargingsocket_is_charging'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='battery_level',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),

        migrations.RunSQL("update app_cs_chargingstation set battery_level = floor(random() * 100 + 1);",
                          reverse_sql=migrations.RunSQL.noop),
    ]
