# Generated by Django 4.1.5 on 2023-02-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cs', '0006_chargingstation_battery_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='vehicle_charged',
            field=models.PositiveBigIntegerField(default=0),
        ),

        migrations.RunSQL("update app_cs_chargingstation set vehicle_charged = floor(random() * 100000 + 1);",
                          reverse_sql=migrations.RunSQL.noop),
    ]
