version: '3'

services:
  cmsp_frontend:
    container_name: cmsp_frontend
    restart: on-failure
    build:
      context: .
    ports:
      - "3001:3000"
    environment:
      - BASE_URL=http://161.35.153.88:8001/api
      - BROWSER_BASE_URL=http://161.35.153.88:8001/api
