# Generated by Django 4.1.5 on 2023-01-13 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_cs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Booked', 'Booked'), ('Charging', 'Charging'), ('Expired', 'Expired'), ('Done', 'Done')], default='Booked', max_length=16)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('charging_stared_at', models.DateTimeField(blank=True, null=True)),
                ('unique_code', models.UUIDField(default=uuid.uuid1, unique=True)),
                ('price', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charging_socket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_cs.chargingsocket')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking History',
                'verbose_name_plural': 'Booking Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bookinghistory',
            index=models.Index(fields=['start_time', 'end_time', 'charging_socket', 'status'], name='app_booking_start_t_765794_idx'),
        ),
    ]
