# Generated by Django 4.1.5 on 2023-01-22 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cs', '0004_alter_chargingstation_power_source'),
        ('app_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinghistory',
            name='charging_socket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sockets', related_query_name='sockets', to='app_cs.chargingsocket'),
        ),
    ]
