# Generated by Django 4.1.5 on 2023-02-03 11:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_dso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dso',
            name='identifier',
            field=models.CharField(default=uuid.uuid1, max_length=256, unique=True),
        ),
    ]
